services:
  postgres:
    image: postgres:16-alpine
    container_name: codenix-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: codenix
      POSTGRES_PASSWORD: codenix
      POSTGRES_DB: codenix_dev
    ports:
      - "5434:5432"
    volumes:
      - codenix_pg_data:/var/lib/postgresql/data

  postgres_test:
    image: postgres:16-alpine
    container_name: codenix-postgres-test
    restart: unless-stopped
    environment:
      POSTGRES_USER: codenix
      POSTGRES_PASSWORD: codenix
      POSTGRES_DB: codenix_test
    ports:
      - "5433:5432"

  redis:
    image: redis:7-alpine
    container_name: codenix-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - codenix_redis_data:/data

volumes:
  codenix_pg_data:
  codenix_redis_data:
